//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by fstest.rc
//
#define IDI_FSTEST                      107
#define DLG_MAIN                        142
#define IDR_FILEMENU                    143
#define IDD_ABOUT                       144
#define IDD_SELECTFORMATIONS            145
#define DLG_TABRANDOMS                  146
#define DLG_TABBLOCKS                   147
#define IDB_BW_1                        150
#define IDB_BW_2                        151
#define IDB_BW_3                        152
#define IDB_BW_4                        153
#define IDB_BW_5                        154
#define IDB_BW_6                        155
#define IDB_BW_7                        156
#define IDB_BW_8                        157
#define IDB_BW_9                        158
#define IDB_BW_10                       159
#define IDB_BW_11                       160
#define IDB_BW_12                       161
#define IDB_BW_13                       162
#define IDB_BW_14                       163
#define IDB_BW_15                       164
#define IDB_BW_16                       165
#define IDB_BW_17                       166
#define IDB_BW_18                       167
#define IDB_BW_19                       168
#define IDB_BW_20                       169
#define IDB_BW_21                       170
#define IDB_BW_22                       171
#define IDB_BW_A                        172
#define IDB_BW_B                        173
#define IDB_BW_C                        174
#define IDB_BW_D                        175
#define IDB_BW_E                        176
#define IDB_BW_F                        177
#define IDB_BW_G                        178
#define IDB_BW_H                        179
#define IDB_BW_J                        180
#define IDB_BW_K                        181
#define IDB_BW_L                        182
#define IDB_BW_M                        183
#define IDB_BW_N                        184
#define IDB_BW_O                        185
#define IDB_BW_P                        186
#define IDB_BW_Q                        187
#define IDB_COL_1                         188
#define IDB_COL_2                         189
#define IDB_COL_3                         190
#define IDB_COL_4                         191
#define IDB_COL_5                         192
#define IDB_COL_6                         193
#define IDB_COL_7                         194
#define IDB_COL_8                         195
#define IDB_COL_9                         196
#define IDB_COL_10                        197
#define IDB_COL_11                        198
#define IDB_COL_12                        199
#define IDB_COL_13                        200
#define IDB_COL_14                        201
#define IDB_COL_15                        202
#define IDB_COL_16                        203
#define IDB_COL_17                        204
#define IDB_COL_18                        205
#define IDB_COL_19                        206
#define IDB_COL_20                        207
#define IDB_COL_21                        208
#define IDB_COL_22                        209
#define IDB_COL_A                         210
#define IDB_COL_B                         211
#define IDB_COL_C                         212
#define IDB_COL_D                         213
#define IDB_COL_E                         214
#define IDB_COL_F                         215
#define IDB_COL_G                         216
#define IDB_COL_H                         217
#define IDB_COL_J                         218
#define IDB_COL_K                         219
#define IDB_COL_L                         220
#define IDB_COL_M                         221
#define IDB_COL_N                         222
#define IDB_COL_O                         223
#define IDB_COL_P                         224
#define IDB_COL_Q                         225
#define IDB_BLANK                       226
#define IDC_FS_PICTURE                  1000
#define IDC_TABBLOCKS_BLOCKPICTURE      1001
#define IDC_FS_ANS_NAME                 1003
#define IDC_FS_ANS_LETTER               1004
#define IDC_TABBLOCKS_BLOCK_ANS1        1005
#define IDC_FS_RESULT_LETTER            1006
#define IDC_FS_RESULT_NAME              1007
#define IDC_GIVEUP                      1010
#define IDC_VER                         1011
#define IDC_TABBLOCKS_NUMBER_ANS        1011
#define IDC_SELECTFORMATIONS_NAME       1012
#define IDC_TABBLOCKS_BLOCK_RESULT1     1012
#define IDC_SELECTAAFORMATIONS          1014
#define IDC_SELECTAAAFORMATIONS         1016
#define IDC_SELECTAFORMATIONS           1017
#define IDC_TABCTRL                     1019
#define IDC_TABBLOCKS_BLOCK_RESULT2     1022
#define IDC_TABBLOCKS_BLOCK_ANS2        1023
#define IDC_TABBLOCKS_NUMBER_RESULT     1024
#define ID_FILE_EXIT                    32771
#define ID_HELP_ABOUT                   32772
#define ID_HELP                         32773
#define ID_HELP_CONTENTS                32774
#define ID_OPTIONS_CHEATMODE            32775
#define ID_OPTIONS_SYNCLETTER           32776
#define ID_OPTIONS_RANDOMS              32777
#define ID_OPTIONS_BLOCKS               32778
#define ID_SHOWFORMATION                32779
#define ID_OPTIONS_SELECTFORMATIONS     32781
#define ID_OPTIONS_COLOURPICS           32783
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        237
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1033
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
